### ISSUE TITLE
Feature 6: User can sign up

### ISSUE THREAD

**Issue by michael-suh** [michael-suh/Final-Project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can sign up for the website by clicking on user logo

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![ffeature 5 D](https://user-images.githubusercontent.com/97069037/171931936-0ef31182-c283-49fe-8166-f6fc9dc6e2d7.PNG)
![ffeature 5 M](https://user-images.githubusercontent.com/97069037/171931959-4f23819c-4ecb-49f4-9980-1d0624341e95.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [ ] Create sign-up.jsx 
- [ ] Integrate google maps API to locate the user's location. 
- [ ] Fetch google maps geocode API
- [ ] create argon2.hash for password
- [ ] Alert when user completes the sign-up

### 🐘 Database

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server

- [ ] Update `server/index.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
